import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import { RootProvider } from '@/providers/root-provider'

import './globals.css'

const interSans = Nunito({
  display: 'auto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${interSans.className}  antialiased`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  )
}
